### ISSUE TITLE
Command failed: import -silent -window root - crop 1920x1080+1280+0 -screen png"-" /bin/sh: 1: import: not found

### ISSUE THREAD

**Issue by doggo404** [JakeMakesStuff/MagicCap#223]
Command failed: import -silent -window root - crop 1920x1080+1280+0 -screen png"-" /bin/sh: 1: import: not found
Happens when i attempt to capture screen.

**Comment by doggo404** [comment]
pop_OS by the way.

**Comment by kekkodance** [comment]
bruh fix dis pls im on windows till u fix

**Comment by v4violet** [comment]
the import command is from imagemagick, you can install imagemagick on pop_os by running 
```bash
sudo apt install imagemagick
```

**Comment by trentwiles** [comment]
That does the trick, thanks.

**Comment by SunburntRock89** [comment]
> That does the trick, thanks.
