### ISSUE TITLE
Please setup some sort of wiki or documentation

### ISSUE THREAD

**Issue by DrawThatRedstone** [JakeMakesStuff/MagicCap#32]
title ^^

**Comment by JakeMakesStuff** [comment]
Would some other people mind commenting their opinion below. I think it is fairly self-explanatory, but I could make one if others want it.

**Comment by phantomelon** [comment]
> Would some other people mind commenting their opinion below. I think it is fairly self-explanatory, but I could make one if others want it.

I'd say it's a good idea

**Comment by JakeMakesStuff** [comment]
After getting some more responses via Discord, I decided to make some documentation.
